### PR TITLE
Undo after multiple redos doesn't work properly

### PR DESCRIPTION
**Pull request by danielhusar**
Hey after playing around and learning ember I noticed one bug :)
Undo after multiple redos doesn't work. (I was able to reproduce it in composer as well)
This small change should fix it.

See demo:
screen
)

### CODE REVIEW

**Comment by danielhusar** [comment]
@GavinJoyce

**Comment by paddyobrien** [comment]
:+1:

**Comment by GavinJoyce** [comment]
nice one, :+1:

**Comment by danielhusar** [comment]
Cheers :) 
(I don't have rights so you guys need to merge it.)

**Pull request merged**
